# Generated by Django 3.2.9 on 2022-05-05 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=30, unique=True)),
                ('phone_number', models.IntegerField()),
                ('position', models.CharField(max_length=70)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
