# Generated by Django 3.2.9 on 2022-05-11 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_employee_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
